version: "3"
services:
  evil:
    build: evil
    command: flask run --host 0.0.0.0 --port=8666
    environment:
      FLASK_DEBUG: "true"
    ports:
      - 8666:8666
    volumes:
      - ./evil:/app

  victim:
    build: victim
    command: flask run --host 0.0.0.0 --port=5001
    environment:
      FLASK_DEBUG: "true"
    ports:
      - 5001:5001
    volumes:
      - ./victim:/app
